# 1. tf.placeholder(dtype, shape=None, name=None)

## 此函数可以理解为形参，用于定义过程，在执行的时候再赋具体的值

参数：

dtype：数据类型。常用的是tf.float32,tf.float64等数值类型

shape：数据形状。默认是None，就是一维值，也可以是多维，比如[2,3], [None, 3]表示列是3，行不定

name：名称。

In [7]:
import numpy as np
import tensorflow as tf
x = tf.placeholder(tf.float32, shape=(1024, 1024), name='x_input')
y = tf.matmul(x, x)

with tf.Session() as sess:
    #print(sess.run(y))  #ERROR :此处x还没有赋值
    rand_array = np.random.rand(1024, 1024)
    print(sess.run(y, feed_dict={x:rand_array}))

[[247.93758 262.33252 252.84474 ... 252.00511 256.14542 256.41217]
 [249.05824 259.4436  250.6381  ... 249.9413  253.07846 257.53564]
 [248.94102 256.18442 255.69418 ... 251.06767 252.39075 254.81546]
 ...
 [247.85872 255.64233 254.59789 ... 247.35431 251.55591 254.99686]
 [252.54648 258.83997 250.87149 ... 249.53078 256.94928 259.30124]
 [254.61629 252.92197 249.90038 ... 249.31796 255.4857  249.27818]]


# 2. tf.variable_scope和tf.name_scope的用法
tf.name_scope可以让变量有相同的命名，包括tf.get_variable得到的变量，还有tf.Variable的变量

tf.variable_scope可以让变量有相同的命名，只是限于tf.Variable的变量

# tf.summary.histogram
tf.summary.histogram(
    name,
    values,
    collections=None,
    family=None
)

In [38]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()

with tf.variable_scope('V1'):
    a1 = tf.get_variable(name='a1', shape=[1], initializer=tf.constant_initializer(1)) 
    a2 = tf.Variable(tf.random_normal(shape=[2,3], mean=0, stddev=1), name="a2")
    
    
with tf.variable_scope("V2"):
    a3 = tf.get_variable(name="a3", shape=[1], initializer=tf.constant_initializer(1))
    a4 = tf.Variable(tf.random_normal(shape=[2, 3], mean=0, stddev=1), name="a4") 
    
with tf.name_scope('V3'):
    b1 = tf.get_variable(name='b1', shape=[1], initializer=tf.constant_initializer(1)) #ERROR
    b2 = tf.Variable(tf.random_normal(shape=[2,3], mean=0, stddev=1), name="b2")
    
    
with tf.name_scope("V4"):
    b3 = tf.get_variable(name="b3", shape=[1], initializer=tf.constant_initializer(1))# ERROR
    b4 = tf.Variable(tf.random_normal(shape=[2, 3], mean=0, stddev=1), name="b4")    

with tf.Session() as sess:
   
    sess.run(tf.initialize_all_variables())
    print(a1.name)
    print(a2.name)
    print(a3.name)
    print(a4.name)
    print(b1.name)
    print(b2.name)
    print(b3.name)
    print(b4.name)
    

V1/a1:0
V1/a2:0
V2/a3:0
V2/a4:0
b1:0
V3/b2:0
b3:0
V4/b4:0
